name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Новый функционал'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Исправления'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Обслуживание'
    labels:
      - 'chore'
      - 'dependencies'
      - 'refactor'
  - title: '📖 Документация'
    labels:
      - 'documentation'
      - 'docs'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'chore'
  default: patch

template: |
  ## Что изменилось

  $CHANGES

  **Полный список изменений**: [`$PREVIOUS_TAG...v$RESOLVED_VERSION`]($REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
